### ISSUE TITLE
1.20.4 Support? (Velocity 3.3.0)

### ISSUE THREAD

**Issue by DartPower** [Elytrium/LimboAPI#127]
Can you add 1.20.4 Support?
I think new Velocity have a new API maybe. Currently release can't work on Velocity 3.3.0

```
[13:14:00 ERROR]: Couldn't pass ProxyInitializeEvent to limboapi
java.lang.NoSuchMethodError: 'com.velocitypowered.proxy.protocol.packet.Disconnect com.velocitypowered.proxy.protocol.packet.Disconnect.create(net.kyori.adventure.text.Component, com.velocitypowered.api.network.ProtocolVersion)'
        at net.elytrium.limboapi.server.CachedPackets.createDisconnectPacket(CachedPackets.java:55) ~[?:?]
        at net.elytrium.limboapi.server.CachedPackets.lambda$createPackets$0(CachedPackets.java:45) ~[?:?]
        at net.elytrium.limboapi.thirdparty.fastprepare.PreparedPacket.prepare(PreparedPacket.java:131) ~[?:?]
        at net.elytrium.limboapi.injection.packet.PreparedPacketImpl.prepare(PreparedPacketImpl.java:89) ~[?:?]
        at net.elytrium.limboapi.injection.packet.PreparedPacketImpl.prepare(PreparedPacketImpl.java:26) ~[?:?]
        at net.elytrium.limboapi.thirdparty.fastprepare.PreparedPacket.prepare(PreparedPacket.java:117) ~[?:?]
        at net.elytrium.limboapi.injection.packet.PreparedPacketImpl.prepare(PreparedPacketImpl.java:79) ~[?:?]
        at net.elytrium.limboapi.injection.packet.PreparedPacketImpl.prepare(PreparedPacketImpl.java:26) ~[?:?]
        at net.elytrium.limboapi.server.CachedPackets.createPackets(CachedPackets.java:45) ~[?:?]
        at net.elytrium.limboapi.LimboAPI.reload(LimboAPI.java:278) ~[?:?]
        at net.elytrium.limboapi.LimboAPI.onProxyInitialization(LimboAPI.java:246) ~[?:?]
        at net.elytrium.limboapi.Lmbda$3.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[velocity-proxy-3.2.0-SNAPSHOT-all.jar:3.2.0-SNAPSHOT (git-f33ec817)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:597) ~[velocity-proxy-3.2.0-SNAPSHOT-all.jar:3.2.0-SNAPSHOT (git-f33ec817)]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:478) ~[velocity-proxy-3.2.0-SNAPSHOT-all.jar:3.2.0-SNAPSHOT (git-f33ec817)]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
```

And/or this is a Velocity Bug?
I'm using my build (not my version, just my fork of PR in official repo) based on https://github.com/pkt77/Velocity/commit/6c5422621d01bdc6befb047176e06def4ec96854

**Comment by JNNGL** [comment]
Unofficial Velocity builds are not supported

**Comment by hevav** [comment]
We don't support unofficial builds of Velocity, unfortunately things may change in an official Velocity build

**Comment by DartPower** [comment]
Not fully my version, just forked a PR.
But i still wait for Velocity update.

**Comment by MagicTeaMC** [comment]
the pr you mentioned is not velocity 3.3.0

**Comment by Dreeam-qwq** [comment]
It's not Velocity side bug. It is the bug that LimboAPI doesn't support 1.20.3/1.20.4 for now.

**Comment by SiriHackYT** [comment]
> the pr you mentioned is not velocity 3.3.0

It is now :)

**Comment by Quinowell** [comment]
now 3.3.0 is stable
